import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "test_data" / "generated_test_cases.json"
OUTPUT_DIR = ROOT.parent / "tests" / "genai"

# Which metrics use "lower is better" (score <= threshold)
LOWER_IS_BETTER = {"hallucination", "bias"}

# Which endpoints require context/ground_truth and may 500 on empty
REQUIRES_CONTEXT = {"faithfulness", "contextual"}
REQUIRES_GROUND_TRUTH = {"hallucination"}

SPEC_TEMPLATE = '''// Auto-generated by generate_playwright_specs.py
const {{ test, expect }} = require('@playwright/test');
const {{ allure }} = require('allure-playwright');

const testCases = {cases_json};

const successDesc = (score, threshold, metric) =>
  metric === "hallucination" || metric === "bias"
    ? `score ${{score}} <= ${{threshold}} (lower is better)`
    : `score ${{score}} >= ${{threshold}} (higher is better)`;

const expectedSuccess = (score, threshold, metric) =>
  (metric === "hallucination" || metric === "bias")
    ? score <= threshold
    : score >= threshold;

test.describe('Metric: {metric}', () => {{
  for (const tc of testCases) {{
    test(`${{tc.id}}: ${{tc.section}}`, async ({{ request }}) => {{
      const detail = [
        `**Requirement:** ${{tc.requirement}}`,
        ``,
        `**User Query:** ${{tc.user_query}}`,
        ``,
        `**System Prompt:** ${{tc.system_prompt}}`,
        ``,
        `**Expected Answer:** ${{tc.expected_answer}}`,
        ``,
        `**Actual LLM Response:** ${{tc.actual_llm_response !== null ? tc.actual_llm_response : '(not yet evaluated)'}}`,
        ``,
        `**Context:** ${{tc.context || '(empty)'}}`,
        `**Retrieval Context:** ${{tc.retrieval_context || '(empty)'}}`,
        `**Threshold:** ${{tc.threshold}}`,
        `**Demographic Features:** ${{tc.demographic_features ? JSON.stringify(tc.demographic_features) : '(none)'}}`,
      ].join('\\n');

      allure.feature(tc.section);
      allure.story(tc.requirement);
      allure.label('metric', '{metric}');
      allure.label('threshold', String(tc.threshold));
      allure.label('user_query', tc.user_query);
      allure.severity('normal');
      allure.description(detail);

      test.info().annotations = [
        {{ type: 'Requirement', description: tc.requirement }},
        {{ type: 'User Query', description: tc.user_query }},
        {{ type: 'System Prompt', description: tc.system_prompt }},
        {{ type: 'Expected Answer', description: tc.expected_answer }},
        {{ type: 'Actual LLM Response', description: tc.actual_llm_response !== null ? tc.actual_llm_response : '(not yet evaluated)' }},
        {{ type: 'Context', description: tc.context || '(empty)' }},
        {{ type: 'Retrieval Context', description: tc.retrieval_context || '(empty)' }},
        {{ type: 'Threshold', description: String(tc.threshold) }},
        {{ type: 'Demographic Features', description: JSON.stringify(tc.demographic_features) }},
      ];

      let obtainedScore = null;
      let obtainedSuccess = null;
      let apiError = null;

      try {{
        const res = await request.post('/evaluate/{metric}', {{
          data: {{
            prompt: tc.prompt,
            response: tc.response,
            context: tc.context || null,
            retrieval_context: tc.retrieval_context || null,
            demographic_features: tc.demographic_features,
          }},
        }});
        if (res.ok()) {{
          const body = await res.json();
          obtainedScore = body.score;
          obtainedSuccess = body.success;
        }} else {{
          apiError = `HTTP ${{res.status()}}: ${{await res.text()}}`;
        }}
      }} catch (e) {{
        apiError = e.message;
      }}

      if (obtainedScore !== null) {{
        const expected = expectedSuccess(obtainedScore, tc.threshold, '{metric}');
        const desc = successDesc(obtainedScore, tc.threshold, '{metric}');

        allure.label('actualScore', String(obtainedScore));
        allure.label('expectedSuccess', String(expected));
        allure.label('actualSuccess', String(obtainedSuccess));

        test.info().annotations.push(
          {{ type: 'Actual Score', description: String(obtainedScore) }},
          {{ type: 'Expected Success', description: String(expected) }},
          {{ type: 'Actual Success', description: String(obtainedSuccess) }},
        );

        expect.soft(obtainedSuccess,
          `[$${{tc.id}}] expected=${{expected}} actual=${{obtainedSuccess}} | score=${{obtainedScore}} threshold=${{tc.threshold}} | ${{desc}}`
        ).toBe(expected);
      }} else {{
        allure.label('actualScore', 'API_ERROR');
        test.info().annotations.push(
          {{ type: 'API Error', description: apiError || 'Unknown error' }},
        );
        expect.soft(false, `[$${{tc.id}}] API call failed: ${{apiError || 'Unknown error'}}`).toBeTruthy();
      }}
    }});
  }}
}});
'''


def generate_specs():
    cases = json.loads(JSON_PATH.read_text(encoding="utf-8"))

    by_metric: dict[str, list] = {}
    for tc in cases:
        by_metric.setdefault(tc["metric"], []).append(tc)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    generated = []
    for metric in ["faithfulness", "relevancy", "contextual", "hallucination", "bias"]:
        metric_cases = by_metric.get(metric, [])
        if not metric_cases:
            continue

        cases_json = json.dumps(metric_cases, indent=2)
        content = SPEC_TEMPLATE.format(
            metric=metric,
            cases_json=cases_json,
        )

        out_path = OUTPUT_DIR / f"{metric}.spec.js"
        out_path.write_text(content, encoding="utf-8")
        generated.append(out_path.name)
        print(f"  ✓ {out_path.name} ({len(metric_cases)} cases)")

    return generated


if __name__ == "__main__":
    print("Generating Playwright spec files...")
    files = generate_specs()
    print(f"\nDone. {len(files)} files generated in {OUTPUT_DIR}")
